vla_path: "/home/v-qilinzhang/model"                          

data_dir: "/home/v-qilinzhang/dataset"                       
dataset_name: "google_robot_close_bottom_drawer"                                
run_root_dir: "/home/v-qilinzhang/runs/0327-0613-dora-baseline"
num_workers: 4                         

epochs: 25                                                
batch_size: 16                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 16                                            
lora_dropout: 0.0
lora_module: [
    "q_proj",
    "lm_head",
    "kv",
    "gate_proj",
    "up_proj",
    "o_proj",
    "fc2",
    "down_proj",
    "qkv",
    "k_proj",
    "fc3",
    "v_proj",
    "q",
    "fc1",
    attn.proj,
    attn_pool.proj,
  ]