vla_path: "/mnt/data-qilin/mr_sqft/OLoRA_more_epochs/google_robot_close_bottom_drawer/merged/epoch49"                          

data_dir: "/mnt/data-qilin/simpler_data_drawer_expanded"                       
dataset_name: "google_robot_close_middle_drawer"                                
run_root_dir: "/mnt/data-qilin/mr_sqft/OLoRA_more_epochs"
num_workers: 4                         

epochs: 50                                                
batch_size: 4                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 16                                            
lora_dropout: 0.0
lora_module: [
    "q_proj",
    "lm_head",
    "kv",
    "gate_proj",
    "up_proj",
    "o_proj",
    "fc2",
    "down_proj",
    "qkv",
    "k_proj",
    "fc3",
    "v_proj",
    "q",
    "fc1",
    attn.proj,
    attn_pool.proj,
  ]       