vla_path: "/mnt/data-qilin/openvla-7b/"                          

data_dir: "/mnt/data-qilin/simpler_data_merged_split/"                       
dataset_name: "google_robot_pick_standing_coke_can"                                
run_root_dir: "/mnt/data-qilin/CL-exp/SingleTaskBaseline/rank1/"
num_workers: 4                         

epochs: 50                                                
batch_size: 4                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 1                                            
lora_dropout: 0.0
lora_module: "all-linear"