vla_path: "/mnt/data-qilin/openvla-7b/"                          

data_dir: "/mnt/data-qilin/simpler_data_split/"                       
dataset_name: "google_robot_open_top_drawer"                                
run_root_dir: "/mnt/data-qilin/LoRA-Baseline/rank8-single-task/"
num_workers: 4                         

epochs: 20                                                
batch_size: 4                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 8                                            
lora_dropout: 0.0
lora_module: "all-linear"