original_path: "/home/v-qilinzhang/openvla-7b"
run_root_path: "/home/v-qilinzhang/runs/0306-2113-Test/google_robot_close_bottom_drawer"
module_name: "language_model.model.layers.22.self_attn.v_proj"
statistics_path: "/home/v-qilinzhang/statics/0307-1600-Test"