vla_path: "openvla-7b"                          

pizza_dir: "dataset"                       
dataset_name: "simpler-65"                                
run_root_dir: "runs"                         
adapter_tmp_dir: "runs/adapter"                                                      

epochs: 30                                                
batch_size: 3                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 2                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 8                                            
lora_dropout: 0.0                                                                       