vla_path: "/datahdd_8T/zql/CL-Adapter/openvla-7b"                          

pizza_dir: "/datahdd_8T/zql/CL-Adapter/dataset"                       
dataset_name: "simpler-65"                                
run_root_dir: "/datahdd_8T/zql/CL-Adapter/runs/0217-TestRepo"                         
adapter_tmp_dir: "/datahdd_8T/zql/CL-Adapter/runs/0217-TestRepo/adapter_tmp"                                                      

epochs: 30                                                
batch_size: 4                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 2                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 8                                            
lora_dropout: 0.0                                                                       