vla_path: "/datahdd_8T/zql/CL-Adapter/openvla-7b"                          

pizza_dir: "/datahdd_8T/zql/CL-Adapter/dataset"                       
dataset_name: "simpler-65"                                
run_root_dir: "/datahdd_8T/zql/CL-Adapter/runs/0224-32Rank"                         
adapter_tmp_dir: "/datahdd_8T/zql/CL-Adapter/runs/0224-32Rank/adapter"                                                      

epochs: 50                                                
batch_size: 8                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 32                                            
lora_dropout: 0.0
lora_module: "all-linear"
#lora_module: ["proj", "qkv", "fc1", "fc2", "fc3"]                                                                       