vla_path: "/mnt/data-qilin/openvla-7b/"                          

pizza_dir: "/mnt/data-xiaofan/robot_dataset/simpler_data/"                       
dataset_name: "simpler-blob"                                
run_root_dir: "/mnt/data-qilin/openvla_simpler_cl/0220-CheckPeft/"                         
adapter_tmp_dir: "/mnt/data-qilin/openvla_simpler_cl/0220-CheckPeft/adapter/"                                                      

epochs: 30                                                
batch_size: 4                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 2                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 8                                            
lora_dropout: 0.0                                                                       