vla_path: "/home/v-qilinzhang/openvla-7b"                          

data_dir: "/home/v-qilinzhang/simpler_data_fordebug"                       
dataset_name: "simpler_data"                                
run_root_dir: "/home/v-qilinzhang/runs/0305-2156-sandbox"
num_workers: 4                         

epochs: 25                                                
batch_size: 20                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 1                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 16                                            
lora_dropout: 0.0
lora_module: "all-linear"
#lora_module: ["proj", "qkv", "fc1", "fc2", "fc3"]                                                                       